"use client";

import React from "react";
import { format as formatDateFns } from "date-fns";

/* ------------------------------------------
   Types
------------------------------------------- */

type Company = {
  name?: string;
  address?: string;
  gstin?: string;
  logoURL?: string;
};

type LineItem = {
  desc: string;
  qty: number;
  rate: number;
};

/* ------------------------------------------
   Helpers
------------------------------------------- */

function formatCurrencyINR(value: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
}

function safeFormatDate(date: string) {
  if (!date) return "";
  try {
    return formatDateFns(new Date(date), "dd MMM yyyy");
  } catch {
    return date;
  }
}

/* ------------------------------------------
   Component
------------------------------------------- */

type Props = {
  id: string;
  client: string;
  date: string;
  lineItems: LineItem[];
  subtotal: number;
  taxAmount: number;
  total: number;
  notes: string;
  company?: Company;
};

export default function InvoicePreview({
  id,
  client,
  date,
  lineItems,
  subtotal,
  taxAmount,
  total,
  notes,
  company,
}: Props) {
  return (
    <div className="print-wrapper">
      <div className="invoice-paper">
        {/* HEADER */}
        <header className="flex justify-between items-start">
          <div>
            <h1 className="text-2xl font-bold">INVOICE</h1>

            {company?.name && (
              <div className="mt-3 text-sm text-slate-600">
                <div className="font-semibold text-slate-800">
                  {company.name}
                </div>
                {company.address && <div>{company.address}</div>}
                {company.gstin && <div>GSTIN: {company.gstin}</div>}
              </div>
            )}

            <div className="mt-4 text-sm text-slate-700">
              <div className="font-semibold">Bill To:</div>
              <div>{client || "Client Name"}</div>
            </div>
          </div>

          <div className="text-right text-sm">
            {company?.logoURL && (
              <img
                src={company.logoURL}
                alt="Company Logo"
                className="h-12 mb-3 ml-auto object-contain"
              />
            )}

            <div>
              <span className="text-slate-600">Invoice # </span>
              <strong>{id}</strong>
            </div>

            <div className="text-slate-600">
              {safeFormatDate(date)}
            </div>
          </div>
        </header>

        {/* TABLE */}
        <table className="w-full mt-10 text-sm border-collapse">
          <thead>
            <tr className="border-b border-slate-300 text-slate-600">
              <th className="text-left pb-3">Description</th>
              <th className="text-left pb-3">Qty</th>
              <th className="text-left pb-3">Rate</th>
              <th className="text-right pb-3">Amount</th>
            </tr>
          </thead>

          <tbody>
            {lineItems.map((li, i) => (
              <tr key={i} className="border-b border-slate-200">
                <td className="py-4">{li.desc}</td>
                <td>{li.qty}</td>
                <td>{formatCurrencyINR(li.rate)}</td>
                <td className="text-right">
                  {formatCurrencyINR(li.qty * li.rate)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* TOTALS */}
        <div className="mt-8 flex justify-end">
          <div className="w-64 text-sm">
            <div className="flex justify-between py-1">
              <span className="text-slate-600">Subtotal</span>
              <span>{formatCurrencyINR(subtotal)}</span>
            </div>

            <div className="flex justify-between py-1">
              <span className="text-slate-600">Tax</span>
              <span>{formatCurrencyINR(taxAmount)}</span>
            </div>

            <div className="flex justify-between py-3 border-t border-slate-300 text-lg font-bold">
              <span>Total</span>
              <span>{formatCurrencyINR(total)}</span>
            </div>
          </div>
        </div>

        {/* NOTES */}
        {notes && (
          <div className="mt-10 text-sm text-slate-700">
            <div className="font-semibold mb-2">Notes</div>
            <div className="bg-slate-100 p-4 rounded">
              {notes}
            </div>
          </div>
        )}

        {/* FOOTER */}
        <footer className="mt-16 text-xs text-slate-400 text-center">
          Generated by Cosmi
        </footer>
      </div>
    </div>
  );
}
